dist: bionic
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
before_install:
  # install chinese font
  - sudo apt-get install -y language-pack-zh-hant fonts-wqy-microhei ttf-wqy-microhei fonts-wqy-zenhei ttf-wqy-zenhei
  # install emoji font
  - sudo apt purge --autoremove fonts-noto-color-emoji
  # update font cache
  - sudo fc-cache -f -v
install:
  - npm install
script:
  - npm run ci-lint
  - npm run build
  - npm run ci-deploy
true:
  branch: master